model:
  merge: True
  start_epoch: 0
  device: "cuda"
  use_ddp: False
  use_mixtrain: True
  only_test: True
  IMG_H: 440
  IMG_W: 408
  load_weights: True
  model_weights: "/nfs/samba/数据聚变/气象数据/hefang/pengjian/result/cas_former_30var_440/pretrain/weight/model_19.pth"
  model_loss: "/nfs/samba/数据聚变/气象数据/pengjian/result/cas_former_30var_440/pre_finetune"
  geo: "/nfs/samba/数据聚变/气象数据/hrrr_440_24var_rb/geo.h5"

train:
  train_batch_size: 8
  loss: "RelativeL2Loss"
  train_input_timestamps: 1
  train_label_timestamps: 1
  variable_weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 7, 5, 5, 9]
  time_weights: [1]
  train_data_path: "/nfs/samba/数据聚变/气象数据/hrrr_440_30var/train"
  optimizer: 
    # name: "SGD"
    # lr: 0.00001
    # weight_decay: 0.0001
    # momentum: 0.9
    name: "AdamW"
    lr: 0.0001
    weight_decay: 0.0001
  scheduler:
    name: "CosineAnnealingLR"
    T_max: 40
    eta_min: 0.00000001
    last_epoch: -1
  # name: "ReduceLROnPlateau"
  # factor: 0.1
  # patience: 3
    
test:
  test_batch_size: 1
  test_data_path: "/nfs/samba/数据聚变/气象数据/hrrr_440_30var/test"
  test_input_timestamps: 1
  test_label_timestamps: 48
# 创建好model_weights_loss文件夹，下面有 weight、rmse、acc 文件夹，有training_batch.log、test_batch.log、epoch_loss.json文件
  